name: flutter_geopackage
description: A module to support OGC geopackage with sqlite.
version: 0.4.7
homepage: https://github.com/moovida/flutter_geopackage
repository: https://github.com/moovida/flutter_geopackage
issue_tracker: https://github.com/moovida/flutter_geopackage/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intl: '>=0.16.1 <=0.17.0'

  # MIT -> added to help chose dart_hydrologis_db the right version for the dev channel
  #        can be removed once null-safety has been reached
  sqlite3: '>=0.1.8 <=1.0.0'

  dart_hydrologis_db: ^0.6.2
    # path: ../dart_hydrologis_db/
    #  git:
    #    url: https://github.com/moovida/dart_hydrologis_db.git

  dart_jts: ^0.1.0
#    git:
#      url: https://github.com/moovida/dart_jts.git

  # MIT
  proj4dart: ^1.0.5


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  dart_hydrologis_utils: ^0.5.4

