name: flutter_geopackage
description: A module to support OGC geopackage with sqlite.
version: 0.2.1+1
homepage: https://github.com/moovida/flutter_geopackage
repository: https://github.com/moovida/flutter_geopackage
issue_tracker: https://github.com/moovida/flutter_geopackage/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intl: ^0.16.1

  dart_hydrologis_db: ^0.2.1
    # path: ../dart_hydrologis_db/
    #  git:
    #    url: https://github.com/moovida/dart_hydrologis_db.git

  dart_jts: ^0.0.5+6
#    git:
#      url: https://github.com/moovida/dart_jts.git


  # MIT
  moor_ffi: ^0.7.0
    # git:
    #   url: https://github.com/moovida/moor.git
    #   ref: develop
    #   path: moor_ffi

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  dart_hydrologis_utils: ^0.5.1

